# Generated by Django 5.2 on 2025-04-24 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 19, 26, 30, 260270, tzinfo=datetime.timezone.utc)),
        ),
    ]
