# Generated by Django 5.2 on 2025-04-24 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_alter_cashflow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
