# Generated by Django 5.2 on 2025-04-26 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0005_alter_status_name_alter_status_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
